openapi: 3.0.0
info:
  title: SparkBank API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_type:
                  type: string
                id_number:
                  type: string
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone:
                  type: string
                address:
                  type: string
                birth_date:
                  type: string
                  format: date
              required:
                - id_type
                - id_number
                - name
                - email
                - password
                - phone
                - address
                - birth_date
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      id_type:
                        type: string
                      id_number:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      address:
                        type: string
                      birth_date:
                        type: string
                        format: date
                      registration_date:
                        type: string
                        format: date-time
                      status:
                        type: string
                      created:
                        type: string
                        format: date-time
                      created_by:
                        type: string
                      updated:
                        type: string
                        format: date-time
                      updated_by:
                        type: string
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /accounts:
    post:
      summary: Crear una nueva cuenta bancaria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_type:
                  type: string
                initial_balance:
                  type: number
              required:
                - account_type
                - initial_balance
      responses:
        '201':
          description: Cuenta creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  account_number:
                    type: string
                  account_type:
                    type: string
                  balance:
                    type: number
                  user_id:
                    type: string
                  created:
                    type: string
                    format: date-time
                  created_by:
                    type: string
                  updated:
                    type: string
                    format: date-time
                  updated_by:
                    type: string
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /users/{id}/accounts:
    get:
      summary: Obtener cuentas de un usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de cuentas del usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    account_number:
                      type: string
                    account_type:
                      type: string
                    balance:
                      type: number
                    created:
                      type: string
                      format: date-time
                    status:
                      type: string
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /login/user:
    post:
      summary: Iniciar sesión de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_type:
                  type: string
                id_number:
                  type: string
                password:
                  type: string
              required:
                - id_type
                - id_number
                - password
      responses:
        '201':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  userid:
                    type: string
                  name:
                    type: string
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /logout/user:
    post:
      summary: Cerrar sesión de usuario
      responses:
        '201':
          description: Cierre de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    type: boolean
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /system/{type}:
    get:
      summary: Obtener configuraciones del sistema
      parameters:
        - in: path
          name: type
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Configuraciones del sistema
        '400':
          description: Error en la solicitud

  /transactions:
    post:
      summary: Crear una nueva transacción
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_account_id:
                  type: string
                source_account_number:
                  type: string
                destination_account_number:
                  type: string
                amount:
                  type: number
                description:
                  type: string
              required:
                - source_account_id
                - destination_account_number
                - amount
      responses:
        '201':
          description: Transacción creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  source_account_id:
                    type: string
                  source_account_number:
                    type: string
                  destination_account_id:
                    type: string
                  destination_account_number:
                    type: string
                  amount:
                    type: number
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /accounts/{accountId}/transactions:
    get:
      summary: Obtener historial de transacciones de una cuenta
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Historial de transacciones de la cuenta
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    source_account_id:
                      type: string
                    source_account_number:
                      type: string
                    destination_account_id:
                      type: string
                    destination_account_number:
                      type: string
                    amount:
                      type: number
                    description:
                      type: string
                    date:
                      type: string
                      format: date-time
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
